### ISSUE TITLE
Create bug-report command

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos-utils#142]
Useful information for solving reported bugs:
- kytos-utils
  - version
    - number
    - GitHub (with hash) or pypi install?
  - installed NApps and versions (simple: kytos napps list)
- python-openflow
  - version
    - number
    - GitHub (with hash) or pypi install?
- kytos
  - version
    - number
    - GitHub (with hash) or pypi install?

**Comment by diraol** [comment]
The kytos/kytos#601 PR may help, I've added lot's of commands and information over there to help getting some of the information listed here (and others)
