### ISSUE TITLE
Change Kytos skel location

### ISSUE THREAD

**Issue by phls** [kytos/kytos-utils#195]
Hi,

There is a bug reported in Debian about to use /etc/skel/kytos directory.

You can read here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887118

I can't update kytos-utils package becasuse of that.

**Comment by beraldoleal** [comment]
Thanks @phls . 

@hdiogenes We should think on a better place to put the Network Applications skel.

**Comment by hdiogenes** [comment]
OK, @beraldoleal. I think `/etc/kytos/skel` will do it.

**Comment by beraldoleal** [comment]
@hdiogenes what is the status on this?
