### ISSUE TITLE
Fix for skel path can break kytos-utils installation

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos-utils#198]
Fix for #195 breaks install in some cases.

**Comment by gleybersonandrade** [comment]
One possible solution is to create the directory, tested by the command:

mkdir -p .direnv/python-3.6.6/etc/kytos/skel

**Comment by gleybersonandrade** [comment]
One possible solution is to create the directory, tested by the command:

mkdir -p .direnv/python-3.6.6/etc/kytos/skel

**Comment by hdiogenes** [comment]
Fixed on #206.
