### ISSUE TITLE
kytos should not upload files present in .gitignore

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/kytos-utils#221]
Today, kytos-utils is uploading some files that cannot be uploaded, like `.vscode` and `.idea`.

**Comment by hdiogenes** [comment]
Like Jason, I'm back on a Friday 13th... (should have been fixed on #220, but it's happening again)

**Comment by gleybersonandrade** [comment]
> Like Jason, I'm back on a Friday 13th... (should have been fixed on #220, but it's happening again)

o.O Friday 13th really isn't a good day kkk Another PR we can take a look is the #241

**Comment by hdiogenes** [comment]
- https://stackoverflow.com/questions/3719243/best-practices-for-adding-gitignore-file-for-python-projects
