### ISSUE TITLE
Error when installing local NApps

### ISSUE THREAD

**Issue by MarvinTorres** [kytos/kytos-utils#278]
I found this issue in 2020.1b3 and had to rollback kytos, kytos-utils, and python-openflow to 2019.1 to successfully enable a custom NApp. I am running Ubuntu 18.04.4.

Reproduction steps:

> 1. Create a Python 3.6 virtual environment with `python3.6 -m venv env`
> 2. Activate the virtual environment with `source env/bin/activate`
> 3. Execute the following commands inside of the _env_ folder:
> ```
> pip install --upgrade pip setuptools wheel
> 
> for repo in python-openflow kytos-utils kytos; do
> git clone https://github.com/kytos/${repo}
> done
> 
> for repo in python-openflow kytos-utils kytos; do
> cd ${repo}
> python3 setup.py develop
> cd ..
> done
> ```
> 4. Run `kytosd -f`
> 5. Run `kytos napps create` and create an NApp with any server username, NApp name, and description
> 6. Run `kytos napps install <username>/<NApp name>`
> 

Result:
> ```
> INFO    NApp test/helloworld:
> INFO      Downloading from NApps Server...
> ERROR Error installing the NApp.
> INFO      Downloaded and installed.
> INFO      Enabling...
> ERROR NApp is not installed. Check the NApp list.
> ERROR     Error enabling NApp.
> Traceback (most recent call last):
>   File "/home/me/env/bin/kytos", line 7, in <module>
>     exec(compile(f.read(), __file__, 'exec'))
>   File "/home/me/env/kytos-utils/bin/kytos", line 50, in <module>
>     parse(argv)
>   File "/home/me/env/kytos-utils/kytos/cli/commands/napps/parser.py", line 52, in parse
>     call(sys.argv[2], args)
>   File "/home/me/env/kytos-utils/kytos/cli/commands/napps/parser.py", line 63, in call
>     func(args)
>   File "/home/me/env/kytos-utils/kytos/cli/commands/napps/api.py", line 129, in install
>     cls.install_napps(args['<napp>'])
>   File "/home/me/env/kytos-utils/kytos/cli/commands/napps/api.py", line 152, in install_napps
>     napp_dependencies = mgr.dependencies()
>   File "/home/me/env/kytos-utils/kytos/utils/napps.py", line 175, in dependencies
>     napps = self._get_napp_key('napp_dependencies', user, napp)
>   File "/home/me/env/kytos-utils/kytos/utils/napps.py", line 206, in _get_napp_key
>     meta = json.loads(urllib.request.urlopen(uri).read())
>   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 400: BAD REQUEST
> ```

In addition, the Kytos controller prints this message:
> ```
> 2020-06-04 14:50:48,738 - ERROR [kytos.core.controller] (Thread-32) Exception on /api/kytos/core/napps/test/helloworld/install [GET]
> Traceback (most recent call last):
>   File "/home/me/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/me/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/me/env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/home/me/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/me/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/home/me/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/me/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/me/env/kytos/kytos/core/api_server.py", line 427, in _install_napp
>     if not self.napps_manager.install(napp, enable=True):
>   File "/home/me/env/kytos/kytos/core/napps/manager.py", line 53, in install
>     pkg_folder = napp.download()
>   File "/home/me/env/kytos/kytos/core/napps/base.py", line 133, in download
>     package_filename = urllib.request.urlretrieve(self.package_url)[0]
>   File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
>     with contextlib.closing(urlopen(url, data)) as fp:
>   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> ```

**Comment by MarvinTorres** [comment]
I noticed that older versions of Kytos look for the NApp in the local file system before searching online.

This is from the [REST API tutorial](https://tutorials.kytos.io/napps/restful_statistics/) on tutorials.kytos.io.

> ```
> $ kytos napps install kytos/of_stats
>
> INFO  NApp kytos/of_stats:
> INFO    Searching local NApp...
> INFO    Not found. Downloading from NApps Server...
> INFO    Downloaded and installed.
> INFO    Enabling...
> INFO    Enabled.
> ```

**Comment by josemauro** [comment]
Hey Marvin, I followed the steps and I had exactly the same problems. I'm already working to solve them. Thank you for open this issue.
