### ISSUE TITLE
LZMA does not work in Debian, Ubuntu

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos-utils#28]
Python 3.6.0 can raise exception trying to import "_lzma" in those distros.

**Comment by diraol** [comment]
@cemsbr, which Debian? Mine worked fine. (Jessie)

**Comment by diraol** [comment]
Are you sure you were using python 3.6?
I'm asking because we use "x:xz" and it was added on python 3.5..... What error was raised exactly?

**Comment by cemsbr** [comment]
We figured it out. This problem only happens if you compile Python and do not include some flags about compression. For Python from distros' repos, this should not be an issue.
