### ISSUE TITLE
Wrong error message to get enabled NApps

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/kytos-utils#282]
The get_enabled() function throws an [Error ](https://github.com/kytos/kytos-utils/blob/a16e539bdd998d0c6a690b83872b837cf6975171/kytos/utils/napps.py#L132)with the message "Error checking installed NApps".
It should be "checking enabled Napps".

**Comment by josemauro** [comment]
Hey, just to let you, I did a PR after saw this issue to fix the problem. Unfortunately, I was not able to the link the PR, seems some bug at GH. 
https://github.com/kytos/kytos-utils/pull/283/
