### ISSUE TITLE
Kytos napps create does not create setup.py

### ISSUE THREAD

**Issue by italovalcy** [kytos/kytos-utils#296]
Hi Guys,

I'm following the Kytos Tutorial "How to create your own NApp: Part 1" (https://tutorials.kytos.io/napps/create_your_napp/), but after running kytos napps create, it does not create the setup.py file.

Steps to reproduce:
1) Create a container using docker kytos/nightly
2) Follow the instructions on Kytos Tutorial  until "Running your NApp"
3) Try to install your newly created napp:
```
$ cd ~/tutorials/<username>/helloworld
$ python setup.py develop
```

Expected behavior:
The napp should be installed

Actual behavior:
```
root@eb14f8d5666f:/kytos-tutorial/italovalcy/helloworld# python setup.py develop
python: can't open file 'setup.py': [Errno 2] No such file or directory
```

**Comment by hdiogenes** [comment]
Worked for me here, @italovalcy. Which `kytos-utils` version are you running?
