### ISSUE TITLE
Fix log name of settings.py template

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos-utils#37]
Now it is, for example, `napps.tutorial.helloworld.settings`. We should remove `settings`.

**Comment by diraol** [comment]
@cemsbr I couldn't understand this... can  you explain it a little better, please?

**Comment by cemsbr** [comment]
The log message includes the log name. When the user writes `log.info('My message')` in his NApp's _main.py_, what we see in Kyco's log is `napps.username.napp.settings` instead of only `napps.username.napp` as the log name, because log is created in _settings.py_. The `settings` part is not necessary for understanding the log (it can even confuse the user) and removing it will make the logs shorter and easier to read.

I'm not sure whether this is the best way to do it, but replacing `logging.getLogger(__name__)` by `logging.getLogger(__name__[:-9])` in _settings.py_ fixes this issue.

If we agree on changing the log name, we should also change it in kyco-utils skel.

**Comment by diraol** [comment]
@cemsbr, fast tought.... what if we did a 'self.log = logging.getLogger(__name__)' on the KycoNApp `__init__`? May be it would work? Then, for the user to log something it would do `self.log.info(<message>)`....

**Comment by cemsbr** [comment]
And then no need to import the log. Although longer (``self.`` prefix), I think it's a better solution.

**Comment by macartur** [comment]
After the refactoration kytos/kytos#287, we can use `self.log.info(<message>)` to write a message in kytos logs and the logger was removed from settings, now we don't need worry about create a log instance.

**Comment by diraol** [comment]
Just to remember that now we have to update our tutorials to be aligned with this changes.

**Comment by cemsbr** [comment]
kytos/kytos#287 dealt with napps' log names.
