### ISSUE TITLE
Kytos napps install should take care of dependencies

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos-utils#60]

**Comment by diraol** [comment]
@cemsbr is this already done?

**Comment by cemsbr** [comment]
Nope. `requirements.txt` is not being installed.

**Comment by cemsbr** [comment]
To clarify, we are talking about installing NApps' requirements.

**Comment by beraldoleal** [comment]
@cemsbr I think that is two things here:

1. If a NApp A depends on NApp B, for sure installing NApp A should install NApp B automatically.
2. If a NApp a depends on some python library (requirements.txt), too (This is tricky, we should discuss before).
