### ISSUE TITLE
Kytos should support enable/disable NApps on-the-fly

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos-utils#92]
When one runs `kytos napps enable foo/bar` the specified NApp is marked and shown as enabled, but will be executed by Kytos only upon next controller restart.
Given we now need Kytos running to manage NApps, the controller should start a NApp as soon as it is enabled and stop a NApp as soon as it is disabled in the command line.

**Comment by cemsbr** [comment]
Closing in favor of #476.

**Comment by beraldoleal** [comment]
@cemsbr #476 where ?

**Comment by renanrodrigo** [comment]
@beraldoleal kytos/kytos#476 AFAIK
